{
    'name': 'Aden',
    'version': '16.0.1.0.0',
    'author': 'Gaston Valles',
    'maintainer': 'Gaston Valles',
    'website': 'https://gastonvalles-portfolio.vercel.app/',
    'license': 'AGPL-3',
    'category': 'Extra Tools',
    'summary': 'Aden Backend Challenge',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/alumno_view.xml',
        'views/programa_view.xml',
        'views/inscripcion_view.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'installable': True,
    'application': True,
}
